# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    # Build morphir application
    - name: Set up node
      uses: actions/setup-node@v1.4.1
      with:
        node-version: '12.14.1'
      
    - name: Set up elm
      uses: justgook/setup-elm@v1
      
    - name: Compile morphir application
      run: |
        npm install -g morphir-elm
        morphir-dapr -d
        
    # Login to Azure Container Registry
    - name: Login to azure container registry
      uses: azure/docker-login@v1
      with: 
        login-server: daprapps.azurecr.io
        username: ${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }}
        password: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
    
    # Build docker image to push to ACR
    - name: Push image to azure container registry
      run: |
        docker build . -t daprapps.azurecr.io/books_and_records:${{ github.sha }}
        docker push daprapps.azurecr.io/books_and_records:${{ github.sha }}
        
    # Login to azure azzount
    - name: Azure login
      uses: azure/login@v1
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Check azure login status #
    - run: |
        az webapp list --query "[?state='Running']" 
 
